### ISSUE TITLE
Still active?

### ISSUE THREAD

**Issue by mattmccullar** [ento/elm-template-ruby#1]
Is this project still active? If so, interested in contributors?

**Comment by ento** [comment]
Not really active (no immediate tasks, not thinking of publishing, etc), and still skeptical of performance, but contributors welcome!

**Comment by mattmccullar** [comment]
Ah, okay. I may fork and create a similar project, or I may do a templates for Sinatra and Rails. These amazing frameworks don't play as well with Elm as they should - for now.
